spring.application.name=api-gateway
server.port=8080

# ?????????????????????????????????????????
# JWT Configuration
# In production: load from environment variable
# or Azure Key Vault ? NEVER hardcode in repo
# ?????????????????????????????????????????
jwt.secret=${JWT_SECRET:SpawnBase2026JwtSecretKeyMustBe32CharsMin!!}
jwt.expiration.ms=${JWT_EXPIRATION_MS:86400000}

# ?????????????????????????????????????????
# ROUTES
# localhost defaults work for local dev.
# Docker Compose overrides via env vars
# using container names for DNS resolution.
# ?????????????????????????????????????????
spring.cloud.gateway.server.webmvc.routes[0].id=metadata-service
spring.cloud.gateway.server.webmvc.routes[0].uri=${METADATA_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/instances/**

spring.cloud.gateway.server.webmvc.routes[1].id=lifecycle-service
spring.cloud.gateway.server.webmvc.routes[1].uri=${LIFECYCLE_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/lifecycle/**

spring.cloud.gateway.server.webmvc.routes[2].id=provisioning-service
spring.cloud.gateway.server.webmvc.routes[2].uri=${PROVISIONING_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/provisioning/**

spring.cloud.gateway.server.webmvc.routes[3].id=credential-service
spring.cloud.gateway.server.webmvc.routes[3].uri=${CREDENTIAL_SERVICE_URL:http://localhost:8084}
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/credentials/**

spring.cloud.gateway.server.webmvc.routes[4].id=admin-service
spring.cloud.gateway.server.webmvc.routes[4].uri=${METADATA_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/admin/**

# ?????????????????????????????????????????
# ACTUATOR
# ?????????????????????????????????????????
#management.endpoints.web.exposure.include=health,info

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=unrestricted