
spring.application.name=metadata-service
server.port=8081


spring.datasource.url=jdbc:postgresql://localhost:5432/spawnbase
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


# update = creates table if not exists, adds new columns
# Never use 'create' in production ? it drops and recreates tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL in logs ? helpful during development
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Format the SQL so it's readable in logs
spring.jpa.properties.hibernate.format_sql=true

# Which DB dialect Hibernate should use
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#management.endpoints.web.exposure.include=health,info

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.access=unrestricted